// <auto-generated />
using System;
using Football.DataAccessEFCore3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Football.DataAccessEFCore3.Migrations
{
    [DbContext(typeof(FootballContext))]
    [Migration("20200709183013_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Abono", b =>
                {
                    b.Property<int>("IdAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_abono")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodCompeticion")
                        .HasColumnName("cod_competicion")
                        .HasColumnType("int");

                    b.Property<int?>("CodZona")
                        .HasColumnName("cod_zona")
                        .HasColumnType("int");

                    b.Property<string>("LoginName")
                        .HasColumnName("loginName")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("IdAbono")
                        .HasName("PK__abono__1E6B9583BC7B6591");

                    b.HasIndex("CodZona");

                    b.HasIndex("LoginName", "CodCompeticion")
                        .IsUnique()
                        .HasName("UQ__abono__4A62EF7D0F85E508")
                        .HasFilter("[loginName] IS NOT NULL AND [cod_competicion] IS NOT NULL");

                    b.ToTable("abono");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Agenda", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_evento")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodCalendario")
                        .HasColumnName("cod_calendario")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnName("tipo")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdEvento")
                        .HasName("PK__agenda__AF150CA507B5EB6B");

                    b.ToTable("agenda");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Arbitro", b =>
                {
                    b.Property<int>("CodArbitro")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Arbitro")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnosActivo")
                        .HasColumnName("Anos_Activo")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Colegio")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Foto")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("CodArbitro")
                        .HasName("PK__Arbitro__C117B4EE6864E33C");

                    b.ToTable("Arbitro");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Asiento", b =>
                {
                    b.Property<int>("CodCompeticion")
                        .HasColumnName("cod_competicion")
                        .HasColumnType("int");

                    b.Property<int>("RefZona")
                        .HasColumnName("ref_zona")
                        .HasColumnType("int");

                    b.Property<int?>("Libres")
                        .HasColumnName("libres")
                        .HasColumnType("int");

                    b.Property<float?>("Precio")
                        .HasColumnName("precio")
                        .HasColumnType("real");

                    b.HasKey("CodCompeticion", "RefZona")
                        .HasName("PK__asiento__2DDFBB74B7935AF9");

                    b.ToTable("asiento");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Calendario", b =>
                {
                    b.Property<int>("CodCalendario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cod_calendario")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodCompeticion")
                        .HasColumnName("cod_Competicion")
                        .HasColumnType("int");

                    b.Property<int>("CodLocal")
                        .HasColumnName("cod_Local")
                        .HasColumnType("int");

                    b.Property<int>("CodVisitante")
                        .HasColumnName("cod_Visitante")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Jornada")
                        .IsRequired()
                        .HasColumnName("jornada")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("MatchCodPartido")
                        .HasColumnType("int");

                    b.HasKey("CodCalendario")
                        .HasName("PK__Calendar__C0C368B419E86DF6");

                    b.HasIndex("MatchCodPartido");

                    b.ToTable("Calendario");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Cambio", b =>
                {
                    b.Property<int>("CodCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Cambio")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodJugadorEntra")
                        .HasColumnName("Cod_Jugador_Entra")
                        .HasColumnType("int");

                    b.Property<int>("CodJugadorSale")
                        .HasColumnName("Cod_Jugador_Sale")
                        .HasColumnType("int");

                    b.Property<int>("CodPartido")
                        .HasColumnName("Cod_Partido")
                        .HasColumnType("int");

                    b.Property<int>("Minuto")
                        .HasColumnType("int");

                    b.HasKey("CodCambio")
                        .HasName("PK__Cambio__82EA1AC42870933A");

                    b.HasIndex("CodJugadorEntra");

                    b.HasIndex("CodJugadorSale");

                    b.HasIndex("CodPartido");

                    b.ToTable("Cambio");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Clasificacion", b =>
                {
                    b.Property<int>("CodCompeticion")
                        .HasColumnName("Cod_Competicion")
                        .HasColumnType("int");

                    b.Property<int>("Jornada")
                        .HasColumnName("jornada")
                        .HasColumnType("int");

                    b.Property<int>("CodEquipo")
                        .HasColumnName("Cod_Equipo")
                        .HasColumnType("int");

                    b.Property<int>("Posicion")
                        .HasColumnName("posicion")
                        .HasColumnType("int");

                    b.Property<int?>("Empatados")
                        .HasColumnName("empatados")
                        .HasColumnType("int");

                    b.Property<int?>("Ganados")
                        .HasColumnName("ganados")
                        .HasColumnType("int");

                    b.Property<int?>("GolesContra")
                        .HasColumnName("goles_contra")
                        .HasColumnType("int");

                    b.Property<int?>("GolesFavor")
                        .HasColumnName("goles_favor")
                        .HasColumnType("int");

                    b.Property<int?>("Perdidos")
                        .HasColumnName("perdidos")
                        .HasColumnType("int");

                    b.Property<int?>("Puntos")
                        .HasColumnName("puntos")
                        .HasColumnType("int");

                    b.HasKey("CodCompeticion", "Jornada", "CodEquipo", "Posicion")
                        .HasName("PK__Clasific__38DD26DC8262AF4E");

                    b.HasIndex("CodEquipo");

                    b.ToTable("Clasificacion");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Comentario", b =>
                {
                    b.Property<int>("CodComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Comentario")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasColumnName("autor")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int>("CodNoticia")
                        .HasColumnName("cod_Noticia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Texto")
                        .HasColumnName("texto")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .HasColumnName("titulo")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("CodComentario")
                        .HasName("PK__Comentar__A48D582F2347E01F");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Competicion", b =>
                {
                    b.Property<int>("CodCompeticion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Competicion")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Campeon")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("CompetitionLogoGlobalMediaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnName("Fecha_Fin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnName("Fecha_Inicio")
                        .HasColumnType("datetime");

                    b.Property<string>("Foto")
                        .HasColumnName("foto")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Temporada")
                        .IsRequired()
                        .HasColumnName("temporada")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Tipo")
                        .HasColumnName("tipo")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("CodCompeticion")
                        .HasName("PK__Competic__EFAD7B6AC59DC2E9");

                    b.HasIndex("CompetitionLogoGlobalMediaId");

                    b.ToTable("Competicion");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Countries", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnName("countryCode")
                        .HasColumnType("nchar(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2);

                    b.Property<string>("LanguageCode")
                        .HasColumnName("languageCode")
                        .HasColumnType("nchar(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnName("countryName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("CountryCode", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Directivo", b =>
                {
                    b.Property<int>("CodIntegrante")
                        .HasColumnName("Cod_Integrante")
                        .HasColumnType("int");

                    b.Property<int>("CodEquipo")
                        .HasColumnName("Cod_Equipo")
                        .HasColumnType("int");

                    b.Property<int>("VersionIntegrante")
                        .HasColumnName("Version_Integrante")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("CodDirectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Directivo")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Profesion")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("CodIntegrante", "CodEquipo", "VersionIntegrante")
                        .HasName("PK__Directiv__80B369C491BE850F");

                    b.HasIndex("CodEquipo");

                    b.ToTable("Directivo");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Entrenador", b =>
                {
                    b.Property<int>("CodIntegrante")
                        .HasColumnName("Cod_Integrante")
                        .HasColumnType("int");

                    b.Property<int>("CodEquipo")
                        .HasColumnName("Cod_Equipo")
                        .HasColumnType("int");

                    b.Property<int>("VersionIntegrante")
                        .HasColumnName("Version_Integrante")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("CodEntrenador")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Entrenador")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("FechaProfesional")
                        .HasColumnName("Fecha_Profesional")
                        .HasColumnType("datetime");

                    b.HasKey("CodIntegrante", "CodEquipo", "VersionIntegrante")
                        .HasName("PK__Entrenad__80B369C4C98831BD");

                    b.HasIndex("CodEquipo");

                    b.ToTable("Entrenador");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Equipo", b =>
                {
                    b.Property<int>("CodEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Equipo")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodEstadio")
                        .HasColumnName("Cod_Estadio")
                        .HasColumnType("int");

                    b.Property<string>("FotoEscudo")
                        .HasColumnName("Foto_Escudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPlantilla")
                        .HasColumnName("Foto_Plantilla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("TeamPictureGlobalMediaId")
                        .HasColumnType("int");

                    b.HasKey("CodEquipo")
                        .HasName("PK__Equipo__FE190172A303E7EF");

                    b.HasIndex("CodEstadio");

                    b.HasIndex("TeamPictureGlobalMediaId");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.EquiposParticipan", b =>
                {
                    b.Property<int>("CodCompeticion")
                        .HasColumnName("Cod_Competicion")
                        .HasColumnType("int");

                    b.Property<int>("CodEquipo")
                        .HasColumnName("Cod_Equipo")
                        .HasColumnType("int");

                    b.HasKey("CodCompeticion", "CodEquipo")
                        .HasName("PK__EquiposP__D04CEB7DEB21C6E3");

                    b.HasIndex("CodEquipo");

                    b.ToTable("EquiposParticipan");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Estadio", b =>
                {
                    b.Property<int>("CodEstadio")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Estadio")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Foto")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int?>("PictureGlobalMediaId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("CodEstadio")
                        .HasName("PK__Estadio__7517D2A58A94C613");

                    b.HasIndex("PictureGlobalMediaId");

                    b.ToTable("Estadio");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.GlobalMedia", b =>
                {
                    b.Property<int>("GlobalMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlobStorageContainer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlobStorageReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GlobalMediaId");

                    b.ToTable("GlobalMedia");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Gol", b =>
                {
                    b.Property<int>("CodGol")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Gol")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodJugador")
                        .HasColumnName("Cod_Jugador")
                        .HasColumnType("int");

                    b.Property<int>("CodPartido")
                        .HasColumnName("Cod_Partido")
                        .HasColumnType("int");

                    b.Property<int>("Minuto")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Video")
                        .HasColumnName("video")
                        .HasColumnType("text");

                    b.HasKey("CodGol")
                        .HasName("PK__Gol__0604040C0A22D869");

                    b.HasIndex("CodJugador");

                    b.HasIndex("CodPartido");

                    b.ToTable("Gol");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.HcoIntegrante", b =>
                {
                    b.Property<int>("CodIntegrante")
                        .HasColumnName("Cod_Integrante")
                        .HasColumnType("int");

                    b.Property<int>("CodEquipo")
                        .HasColumnName("Cod_Equipo")
                        .HasColumnType("int");

                    b.Property<int>("VersionIntegrante")
                        .HasColumnName("Version_Integrante")
                        .HasColumnType("int");

                    b.Property<int?>("Dorsal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnName("Fecha_Fin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaFinContrato")
                        .HasColumnName("Fecha_Fin_Contrato")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnName("Fecha_Inicio")
                        .HasColumnType("datetime");

                    b.Property<float?>("Sueldo")
                        .HasColumnType("real");

                    b.HasKey("CodIntegrante", "CodEquipo", "VersionIntegrante")
                        .HasName("PK__Hco_Inte__80B369C4638A5B22");

                    b.HasIndex("CodEquipo");

                    b.ToTable("Hco_Integrante");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Integrante", b =>
                {
                    b.Property<int>("CodInt")
                        .HasColumnName("Cod_Int")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNac")
                        .HasColumnName("Fecha_Nac")
                        .HasColumnType("datetime");

                    b.Property<string>("Foto")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("PictureGlobalMediaId")
                        .HasColumnType("int");

                    b.HasKey("CodInt")
                        .HasName("PK__Integran__0488816542B2EB29");

                    b.HasIndex("PictureGlobalMediaId");

                    b.ToTable("Integrante");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Jugador", b =>
                {
                    b.Property<int>("CodJugador")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Jugador")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float?>("Altura")
                        .HasColumnType("real");

                    b.Property<int?>("CodEquipo")
                        .HasColumnName("Cod_Equipo")
                        .HasColumnType("int");

                    b.Property<int?>("CodIntegrante")
                        .HasColumnName("Cod_Integrante")
                        .HasColumnType("int");

                    b.Property<bool>("Married")
                        .HasColumnType("bit");

                    b.Property<string>("Pierna")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int?>("VersionIntegrante")
                        .HasColumnName("Version_Integrante")
                        .HasColumnType("int");

                    b.HasKey("CodJugador")
                        .HasName("PK__Jugador__311588804F56E76B");

                    b.HasIndex("CodEquipo");

                    b.HasIndex("CodIntegrante");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Languages", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasColumnName("languageCode")
                        .HasColumnType("nchar(2)")
                        .IsFixedLength(true)
                        .HasMaxLength(2);

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnName("languageName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("LanguageCode");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.LineaPedido", b =>
                {
                    b.Property<int>("Idpedido")
                        .HasColumnName("idpedido")
                        .HasColumnType("int");

                    b.Property<int>("Idlinea")
                        .HasColumnName("idlinea")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Disp")
                        .HasColumnName("disp")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnName("idProducto")
                        .HasColumnType("int");

                    b.Property<float>("Pvp")
                        .HasColumnName("pvp")
                        .HasColumnType("real");

                    b.HasKey("Idpedido", "Idlinea")
                        .HasName("PK__LineaPed__3565A2260C680D70");

                    b.ToTable("LineaPedido");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Medico", b =>
                {
                    b.Property<int>("CodMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Medico")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodEquipo")
                        .HasColumnName("Cod_Equipo")
                        .HasColumnType("int");

                    b.Property<int>("CodIntegrante")
                        .HasColumnName("Cod_Integrante")
                        .HasColumnType("int");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FechaProfesional")
                        .HasColumnName("Fecha_Profesional")
                        .HasColumnType("datetime");

                    b.Property<int>("VersionIntegrante")
                        .HasColumnName("Version_Integrante")
                        .HasColumnType("int");

                    b.HasKey("CodMedico")
                        .HasName("PK__Medico__18937FE2AD662269");

                    b.HasIndex("CodEquipo");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Noticia", b =>
                {
                    b.Property<int>("CodNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Noticia")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasColumnName("autor")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int?>("CodPartido")
                        .HasColumnName("cod_Partido")
                        .HasColumnType("int");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Foto")
                        .HasColumnName("foto")
                        .HasColumnType("text");

                    b.Property<string>("Resumen")
                        .HasColumnType("text");

                    b.Property<string>("SubCategoria")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("CodNoticia")
                        .HasName("PK__Noticia__A76A776C50E2F9FA");

                    b.ToTable("Noticia");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Partido", b =>
                {
                    b.Property<int>("CodPartido")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Partido")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Asistencia")
                        .HasColumnType("int");

                    b.Property<string>("Clima")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("CodArbitro")
                        .HasColumnName("Cod_Arbitro")
                        .HasColumnType("int");

                    b.Property<int>("CodCompeticion")
                        .HasColumnName("Cod_Competicion")
                        .HasColumnType("int");

                    b.Property<int>("CodEstadio")
                        .HasColumnName("Cod_Estadio")
                        .HasColumnType("int");

                    b.Property<int>("CodLocal")
                        .HasColumnName("Cod_Local")
                        .HasColumnType("int");

                    b.Property<int>("CodVisitante")
                        .HasColumnName("Cod_Visitante")
                        .HasColumnType("int");

                    b.Property<int>("CornersLocal")
                        .HasColumnName("Corners_Local")
                        .HasColumnType("int");

                    b.Property<int>("CornersVisitante")
                        .HasColumnName("Corners_Visitante")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("FuerasJuegoLocal")
                        .HasColumnName("Fueras_Juego_Local")
                        .HasColumnType("int");

                    b.Property<int>("FuerasJuegoVisitante")
                        .HasColumnName("Fueras_Juego_Visitante")
                        .HasColumnType("int");

                    b.Property<int>("GolesLocal")
                        .HasColumnName("Goles_Local")
                        .HasColumnType("int");

                    b.Property<int>("GolesVisitante")
                        .HasColumnName("Goles_Visitante")
                        .HasColumnType("int");

                    b.Property<string>("Jornada")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<float>("PosesionLocal")
                        .HasColumnName("Posesion_Local")
                        .HasColumnType("real");

                    b.Property<float>("PosesionVisitante")
                        .HasColumnName("Posesion_Visitante")
                        .HasColumnType("real");

                    b.HasKey("CodPartido")
                        .HasName("PK__Partido__7E512A7A7524CB5D");

                    b.HasIndex("CodArbitro");

                    b.HasIndex("CodCompeticion");

                    b.HasIndex("CodEstadio");

                    b.HasIndex("CodLocal");

                    b.HasIndex("CodVisitante");

                    b.ToTable("Partido");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.PartidoJugado", b =>
                {
                    b.Property<int>("CodJugador")
                        .HasColumnName("Cod_Jugador")
                        .HasColumnType("int");

                    b.Property<int>("CodPartido")
                        .HasColumnName("Cod_Partido")
                        .HasColumnType("int");

                    b.Property<int>("Asistencias")
                        .HasColumnType("int");

                    b.Property<int>("AsistenciasGol")
                        .HasColumnName("Asistencias_Gol")
                        .HasColumnType("int");

                    b.Property<int>("BalonesPerdidos")
                        .HasColumnName("balones_perdidos")
                        .HasColumnType("int");

                    b.Property<int>("BalonesRecuperados")
                        .HasColumnName("balones_recuperados")
                        .HasColumnType("int");

                    b.Property<int>("Corners")
                        .HasColumnName("corners")
                        .HasColumnType("int");

                    b.Property<int>("FaltasCometidas")
                        .HasColumnName("Faltas_Cometidas")
                        .HasColumnType("int");

                    b.Property<int>("FaltasRecibidas")
                        .HasColumnName("Faltas_Recibidas")
                        .HasColumnType("int");

                    b.Property<int>("FuerasJuego")
                        .HasColumnName("fueras_Juego")
                        .HasColumnType("int");

                    b.Property<int>("Minutos")
                        .HasColumnType("int");

                    b.Property<int>("PenaltisCometidos")
                        .HasColumnName("penaltis_cometidos")
                        .HasColumnType("int");

                    b.Property<int>("PenaltisRecibidos")
                        .HasColumnName("penaltis_recibidos")
                        .HasColumnType("int");

                    b.Property<int>("Remates")
                        .HasColumnName("remates")
                        .HasColumnType("int");

                    b.Property<int>("RematesPorteria")
                        .HasColumnName("remates_Porteria")
                        .HasColumnType("int");

                    b.Property<int>("RematesPoste")
                        .HasColumnName("remates_Poste")
                        .HasColumnType("int");

                    b.Property<int>("TarjetasAmarillasProvocadas")
                        .HasColumnName("tarjetas_Amarillas_Provocadas")
                        .HasColumnType("int");

                    b.Property<int>("TarjetasRojasProvocadas")
                        .HasColumnName("tarjetas_Rojas_Provocadas")
                        .HasColumnType("int");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("CodJugador", "CodPartido")
                        .HasName("PK__Partido___86F09A27E3058A54");

                    b.HasIndex("CodPartido");

                    b.ToTable("Partido_Jugado");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Pedidos", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idPedido")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnName("calle")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int>("Cp")
                        .HasColumnName("cp")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("estado")
                        .HasColumnType("varchar(10)")
                        .HasDefaultValueSql("('Pendiente')")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fechatarjeta")
                        .HasColumnName("fechatarjeta")
                        .HasColumnType("datetime");

                    b.Property<string>("IdUsuario")
                        .HasColumnName("idUsuario")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int>("Numero")
                        .HasColumnName("numero")
                        .HasColumnType("int");

                    b.Property<string>("Puerta")
                        .HasColumnName("puerta")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Tarjeta")
                        .IsRequired()
                        .HasColumnName("tarjeta")
                        .HasColumnType("varchar(17)")
                        .HasMaxLength(17)
                        .IsUnicode(false);

                    b.HasKey("IdPedido")
                        .HasName("PK__pedidos__A9F619B737664567");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Producto", b =>
                {
                    b.Property<int>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("prodId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria")
                        .HasColumnName("categoria")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("datetime");

                    b.Property<string>("Foto")
                        .HasColumnName("foto")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<float?>("Precio")
                        .HasColumnName("precio")
                        .HasColumnType("real");

                    b.Property<int?>("Stock")
                        .HasColumnName("stock")
                        .HasColumnType("int");

                    b.HasKey("ProdId")
                        .HasName("PK__Producto__319F67F18283D8BE");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Tarjeta", b =>
                {
                    b.Property<int>("CodTarjeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Tarjeta")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodJugador")
                        .HasColumnName("Cod_Jugador")
                        .HasColumnType("int");

                    b.Property<int>("CodPartido")
                        .HasColumnName("Cod_Partido")
                        .HasColumnType("int");

                    b.Property<int>("Minuto")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("CodTarjeta")
                        .HasName("PK__Tarjeta__D5EE15398F60B8AF");

                    b.HasIndex("CodJugador");

                    b.HasIndex("CodPartido");

                    b.ToTable("Tarjeta");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Transpaso", b =>
                {
                    b.Property<int>("CodTranspaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Transpaso")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodEquipoDestino")
                        .HasColumnName("Cod_Equipo_Destino")
                        .HasColumnType("int");

                    b.Property<int>("CodEquipoOrigen")
                        .HasColumnName("Cod_Equipo_Origen")
                        .HasColumnType("int");

                    b.Property<int>("CodIntegrante")
                        .HasColumnName("Cod_Integrante")
                        .HasColumnType("int");

                    b.Property<float>("Coste")
                        .HasColumnType("real");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.HasKey("CodTranspaso")
                        .HasName("PK__Transpas__94AB3B39BE7F2969");

                    b.HasIndex("CodEquipoDestino");

                    b.HasIndex("CodEquipoOrigen");

                    b.ToTable("Transpaso");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Trata", b =>
                {
                    b.Property<int>("CodTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod_Tratamiento")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodJugador")
                        .HasColumnName("Cod_Jugador")
                        .HasColumnType("int");

                    b.Property<int>("CodMedico")
                        .HasColumnName("Cod_Medico")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnName("Fecha_Fin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnName("Fecha_Inicio")
                        .HasColumnType("datetime");

                    b.Property<string>("Lesion")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("CodTratamiento")
                        .HasName("PK__Trata__17B0DB894F867B70");

                    b.HasIndex("CodJugador");

                    b.HasIndex("CodMedico");

                    b.ToTable("Trata");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.UserProfile", b =>
                {
                    b.Property<string>("LoginName")
                        .HasColumnName("loginName")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnName("country")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("Cp")
                        .HasColumnName("cp")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnName("direccion")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnName("dni")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("EnPassword")
                        .IsRequired()
                        .HasColumnName("enPassword")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("FechaTarjeta")
                        .HasColumnName("fechaTarjeta")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstName")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnName("language")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Localidad")
                        .HasColumnName("localidad")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnName("surname")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Tarjeta")
                        .HasColumnName("tarjeta")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("Telefono")
                        .HasColumnName("telefono")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("LoginName");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.ZonaEstadio", b =>
                {
                    b.Property<int>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_zona")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Capacidad")
                        .HasColumnName("capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Cubierto")
                        .HasColumnName("cubierto")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("IdZona")
                        .HasName("PK__zonaEsta__67C93611F159F2D3");

                    b.ToTable("zonaEstadio");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Abono", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.ZonaEstadio", "CodZonaNavigation")
                        .WithMany("Abono")
                        .HasForeignKey("CodZona")
                        .HasConstraintName("FK__abono__cod_zona__06CD04F7");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Calendario", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Partido", "MatchCodPartidoNavigation")
                        .WithMany("Calendario")
                        .HasForeignKey("MatchCodPartido");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Cambio", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Jugador", "CodJugadorEntraNavigation")
                        .WithMany("CambioCodJugadorEntraNavigation")
                        .HasForeignKey("CodJugadorEntra")
                        .HasConstraintName("FK__Cambio__Cod_Juga__08B54D69")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Jugador", "CodJugadorSaleNavigation")
                        .WithMany("CambioCodJugadorSaleNavigation")
                        .HasForeignKey("CodJugadorSale")
                        .HasConstraintName("FK__Cambio__Cod_Juga__09A971A2")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Partido", "CodPartidoNavigation")
                        .WithMany("Cambio")
                        .HasForeignKey("CodPartido")
                        .HasConstraintName("FK__Cambio__Cod_Part__07C12930")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Clasificacion", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Competicion", "CodCompeticionNavigation")
                        .WithMany("Clasificacion")
                        .HasForeignKey("CodCompeticion")
                        .HasConstraintName("FK__Clasifica__Cod_C__0A9D95DB")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodEquipoNavigation")
                        .WithMany("Clasificacion")
                        .HasForeignKey("CodEquipo")
                        .HasConstraintName("FK__Clasifica__Cod_E__0B91BA14")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Competicion", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.GlobalMedia", "CompetitionLogoGlobalMedia")
                        .WithMany("Competicion")
                        .HasForeignKey("CompetitionLogoGlobalMediaId");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Countries", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Languages", "LanguageCodeNavigation")
                        .WithMany("Countries")
                        .HasForeignKey("LanguageCode")
                        .HasConstraintName("FK_Languages")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Directivo", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodEquipoNavigation")
                        .WithMany("Directivo")
                        .HasForeignKey("CodEquipo")
                        .HasConstraintName("FK__Directivo__Cod_E__0D7A0286")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Entrenador", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodEquipoNavigation")
                        .WithMany("Entrenador")
                        .HasForeignKey("CodEquipo")
                        .HasConstraintName("FK__Entrenado__Cod_E__0E6E26BF")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Equipo", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Estadio", "CodEstadioNavigation")
                        .WithMany("Equipo")
                        .HasForeignKey("CodEstadio");

                    b.HasOne("Football.DataAccessEFCore3.Models.GlobalMedia", "TeamPictureGlobalMedia")
                        .WithMany("Equipo")
                        .HasForeignKey("TeamPictureGlobalMediaId");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.EquiposParticipan", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Competicion", "CodCompeticionNavigation")
                        .WithMany("EquiposParticipan")
                        .HasForeignKey("CodCompeticion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodEquipoNavigation")
                        .WithMany("EquiposParticipan")
                        .HasForeignKey("CodEquipo")
                        .HasConstraintName("FK__EquiposPa__Cod_E__0F624AF8")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Estadio", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.GlobalMedia", "PictureGlobalMedia")
                        .WithMany("Estadio")
                        .HasForeignKey("PictureGlobalMediaId");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Gol", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Jugador", "CodJugadorNavigation")
                        .WithMany("Gol")
                        .HasForeignKey("CodJugador")
                        .HasConstraintName("FK__Gol__Cod_Jugador__114A936A")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Partido", "CodPartidoNavigation")
                        .WithMany("Gol")
                        .HasForeignKey("CodPartido")
                        .HasConstraintName("FK__Gol__Cod_Partido__10566F31")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.HcoIntegrante", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodEquipoNavigation")
                        .WithMany("HcoIntegrante")
                        .HasForeignKey("CodEquipo")
                        .HasConstraintName("FK__Hco_Integ__Cod_E__1332DBDC")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Integrante", "CodIntegranteNavigation")
                        .WithMany("HcoIntegrante")
                        .HasForeignKey("CodIntegrante")
                        .HasConstraintName("FK__Hco_Integ__Cod_I__123EB7A3")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Integrante", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.GlobalMedia", "PictureGlobalMedia")
                        .WithMany("Integrante")
                        .HasForeignKey("PictureGlobalMediaId");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Jugador", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodEquipoNavigation")
                        .WithMany("Jugador")
                        .HasForeignKey("CodEquipo")
                        .HasConstraintName("FK__Jugador__Cod_Equ__14270015");

                    b.HasOne("Football.DataAccessEFCore3.Models.Integrante", "CodIntegranteNavigation")
                        .WithMany("Jugador")
                        .HasForeignKey("CodIntegrante")
                        .HasConstraintName("FK_Jugador_Integrante");
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.LineaPedido", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Pedidos", "IdpedidoNavigation")
                        .WithMany("LineaPedido")
                        .HasForeignKey("Idpedido")
                        .HasConstraintName("FK__LineaPedi__idped__160F4887")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Medico", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodEquipoNavigation")
                        .WithMany("Medico")
                        .HasForeignKey("CodEquipo")
                        .HasConstraintName("FK__Medico__Cod_Equi__17036CC0")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Partido", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Arbitro", "CodArbitroNavigation")
                        .WithMany("Partido")
                        .HasForeignKey("CodArbitro")
                        .HasConstraintName("FK__Partido__Cod_Arb__1AD3FDA4")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Competicion", "CodCompeticionNavigation")
                        .WithMany("Partido")
                        .HasForeignKey("CodCompeticion")
                        .HasConstraintName("FK__Partido__Cod_Com__17F790F9")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Estadio", "CodEstadioNavigation")
                        .WithMany("Partido")
                        .HasForeignKey("CodEstadio")
                        .HasConstraintName("FK__Partido__Cod_Est__1BC821DD")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodLocalNavigation")
                        .WithMany("PartidoCodLocalNavigation")
                        .HasForeignKey("CodLocal")
                        .HasConstraintName("FK__Partido__Cod_Loc__18EBB532")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodVisitanteNavigation")
                        .WithMany("PartidoCodVisitanteNavigation")
                        .HasForeignKey("CodVisitante")
                        .HasConstraintName("FK__Partido__Cod_Vis__19DFD96B")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.PartidoJugado", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Jugador", "CodJugadorNavigation")
                        .WithMany("PartidoJugado")
                        .HasForeignKey("CodJugador")
                        .HasConstraintName("FK__Partido_J__Cod_J__1CBC4616")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Partido", "CodPartidoNavigation")
                        .WithMany("PartidoJugado")
                        .HasForeignKey("CodPartido")
                        .HasConstraintName("FK__Partido_J__Cod_P__1DB06A4F")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Tarjeta", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Jugador", "CodJugadorNavigation")
                        .WithMany("Tarjeta")
                        .HasForeignKey("CodJugador")
                        .HasConstraintName("FK__Tarjeta__Cod_Jug__1F98B2C1")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Partido", "CodPartidoNavigation")
                        .WithMany("Tarjeta")
                        .HasForeignKey("CodPartido")
                        .HasConstraintName("FK__Tarjeta__Cod_Par__1EA48E88")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Transpaso", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodEquipoDestinoNavigation")
                        .WithMany("TranspasoCodEquipoDestinoNavigation")
                        .HasForeignKey("CodEquipoDestino")
                        .HasConstraintName("FK__Transpaso__Cod_E__2180FB33")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Equipo", "CodEquipoOrigenNavigation")
                        .WithMany("TranspasoCodEquipoOrigenNavigation")
                        .HasForeignKey("CodEquipoOrigen")
                        .HasConstraintName("FK__Transpaso__Cod_E__208CD6FA")
                        .IsRequired();
                });

            modelBuilder.Entity("Football.DataAccessEFCore3.Models.Trata", b =>
                {
                    b.HasOne("Football.DataAccessEFCore3.Models.Jugador", "CodJugadorNavigation")
                        .WithMany("Trata")
                        .HasForeignKey("CodJugador")
                        .HasConstraintName("FK__Trata__Cod_Jugad__236943A5")
                        .IsRequired();

                    b.HasOne("Football.DataAccessEFCore3.Models.Medico", "CodMedicoNavigation")
                        .WithMany("Trata")
                        .HasForeignKey("CodMedico")
                        .HasConstraintName("FK__Trata__Cod_Medic__22751F6C")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
